import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { About } from "./about";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+SA+Beginner&family=Edu+VIC+WA+NT+Beginner&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About{" "}
          <Link href="https://www.instagram.com/chatterjee_abhiraj/">
            <a target="_blank">Me</a>
          </Link>
        </h1>

        <p className={styles.description}>Hi !! Abhiraj this side 👋</p>

        <div className={styles.grid}>
          <h2>Who and What I am &rarr;</h2>
        </div>
        <div className={styles.grid}>
          <h2>
            Hello, my name is Abhiraj Chatterjee. I am a final year B.Tech
            Undergrad student studying Computer Science and Engineering at KIIT
            University, Bhubaneswar. Honestly speaking, I am a very free
            spirited person who loves to enjoy life rather than always staying
            entangled in what I am #supposedtodo, but professionally I am a Full
            Stack Developer and am currently working as an Intern at Tata
            Digital (mother organization of the Tata Neu Superapp). I love
            coding, poetry, singing, sketching, anime and making a lot of new
            friends 😉.
          </h2>
        </div>
        <div className={styles.grid}>
          <h2>
            <Link href="/">
              <a>&larr; Go to Home Page</a>
            </Link>
          </h2>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with 😻 by Abhiraj{" "}
        {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      </footer>
    </div>
  );
}
