import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { About } from './about'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abhiraj Chatterjee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
<link href="https://fonts.googleapis.com/css2?family=Edu+SA+Beginner&family=Edu+VIC+WA+NT+Beginner&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        My <Link href="https://github.com/Abhiraj3112000?tab=repositories"><a>Projects</a></Link>
        </h1>

        <p className={styles.description}>
          These are some of my projects with a beautiful UI 🌹
        </p>

        <div className={styles.grid}>
          <Link href="https://smartclass.netlify.app/">
            <a target="_blank" className={styles.card}>
            <h2>Smart Class &rarr;</h2>
            <p>Real-time smart classroom generating application 📚</p>
            </a>
          </Link>

          <Link href="https://communitynotes.netlify.app/">
            <a target="_blank" className={styles.card}>
            <h2>Community Notes &rarr;</h2>
            <p>Personal Note Keeping Web App 📜</p>
            </a>
          </Link>

          <Link href="https://hogwartschat.netlify.app/">
            <a target="_blank" className={styles.card}>
            <h2>Hogwarts Chat &rarr;</h2>
            <p>Anonymous open chatting Web App 🧹 </p>
            </a>
          </Link>

          <Link href="https://drive.google.com/file/d/1Gh82d23qyTOPv4WtmFzwz5wyaBro0hWY/view">
            <a target="_blank" className={styles.card}>
            <h2>AI - Date Prediction &rarr;</h2>
            <p>
              An AI enabled invoice payment date predicting Web App 🤖</p>
            </a>
          </Link>

        </div>
        <div className={styles.grid}>
            <h2><Link href="/"><a>&larr; Go to Home Page</a></Link></h2>
        </div>
      </main>

      <footer className={styles.footer}>
          Made with 😻 by Abhiraj{' '}
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      </footer>
    </div>
  )
}
