import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { About } from "./about";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+SA+Beginner&family=Edu+VIC+WA+NT+Beginner&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My{" "}
          <Link href="https://github.com/Abhiraj3112000">
            <a target="_blank">Techstack</a>
          </Link>
        </h1>

        <p className={styles.description}>
          Get to know the tools I use for developing software 🔨
        </p>

        {/* <div className={styles.grid}>
          
        </div> */}
        <div className={styles.grid}>
        <h2>My Tech Stack &rarr;</h2>
          <ul>
            <li>
              <h2>Languages &rarr; </h2>
              <h3>• C++, Java, JavaScript, TypeScript, Dart, Python</h3>
            </li>
            <li>
              <h2>Web Development &rarr;</h2>
              <h3>• React Js, Next Js, HTML, CSS, JavaScript</h3>
            </li>
            <li>
              <h2>Database/SAAS &rarr;</h2>
              <h3>• Firebase, MySQL</h3>
            </li>
            <li>
              <h2>Mobile App Development &rarr;</h2>
              <h3>• Flutter, Java</h3>
            </li>
            <li>
              <h2>Microservice/Middleware Development &rarr;</h2>
              <h3>• Node Js, Express Js, Java Servlets, JDBC, Flask</h3>
            </li>
            <li>
              <h2>Machine Learning &rarr;</h2>
              <h3>• Python, Scikit Learn, Numpy, Pandas, Seaborn</h3>
            </li>
          </ul>
        </div>
        <div className={styles.grid}>
          <h2>
            <Link href="/">
              <a>&larr; Go to Home Page</a>
            </Link>
          </h2>
        </div>
      </main>

      <footer className={styles.footer}>
        Made with 😻 by Abhiraj{" "}
        {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      </footer>
    </div>
  );
}
